---
title: "NHANES DATA"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

nhanesTable: displays the name of tables corresponding to the year and the type of survey


*Demographics*
```{r}
library(nhanesA)

nhanesTables('DEMO', 2007) #2007 - 2008
nhanesTables('DEMO', 2009) #2009 - 2010
nhanesTables('DEMO', 2011) #2011 - 2012
nhanesTables('DEMO', 2013) #2013 - 2014
nhanesTables('DEMO', 2015) #2015 - 2016
nhanesTables('DEMO', 2017) #2017 - 2018


```


```{r}
#Demographics from the year 2007-2018
dem7_8 <- nhanes("DEMO_E")
dem9_10 <- nhanes("DEMO_F")
dem11_12 <- nhanes("DEMO_G")
dem13_14 <- nhanes("DEMO_H")
dem15_16 <- nhanes("DEMO_I")
dem17_18 <- nhanes("DEMO_J")


 

```



```{r}
library(dplyr) #merge tables using full_join
library(purrr) # package which helps combine more than two tables

dem7_18<- list(dem7_8,dem9_10,dem11_12,dem13_14,dem15_16,dem17_18) %>% reduce(full_join, by = "SEQN")
head(dem7_18,5)

```

*EXAMINATION*

```{r}
nhanesTables('EXAM', 2007) #2007 - 2008
nhanesTables('EXAM', 2009) #2009 - 2010
nhanesTables('EXAM', 2011) #2011 - 2012
nhanesTables('EXAM', 2013) #2013 - 2014
nhanesTables('EXAM', 2015) #2015 - 2016
nhanesTables('EXAM', 2017) #2017 - 2018
```

*LABORATORY*
```{r}
nhanesTables('LAB', 2007) #2007 - 2008
nhanesTables('LAB', 2009) #2009 - 2010
nhanesTables('LAB', 2011) #2011 - 2012
nhanesTables('LAB', 2013) #2013 - 2014
nhanesTables('LAB', 2015) #2015 - 2016
nhanesTables('LAB', 2017) #2017 - 2018

```


*DIETARY*
```{r}

nhanesTables('DIET', 2007) #2007 - 2008
nhanesTables('DIET', 2009) #2009 - 2010
nhanesTables('DIET', 2011) #2011 - 2012
nhanesTables('DIET', 2013) #2013 - 2014
nhanesTables('DIET', 2015) #2015 - 2016
nhanesTables('DIET', 2017) #2017 - 2018

```

*Questionnaire*
```{r}

nhanesTables('Q', 2007) #2007 - 2008
nhanesTables('Q', 2009) #2009 - 2010
nhanesTables('Q', 2011) #2011 - 2012
nhanesTables('Q', 2013) #2013 - 2014
nhanesTables('Q', 2015) #2015 - 2016
nhanesTables('Q', 2017) #2017 - 2018

```






















